version: '3'

services:
  backend:
    image: springbootpart:tag
    ports:
      - "8080:80"
    depends_on:
      - database

  frontend:
    image: angularpart:tag
    ports:
      - "4200:80"
    depends_on:
      - backend

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: fullstackproject
      MYSQL_USER: mariadb
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"